# Generated by Django 5.2.15 on 2026-06-12 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0003_project_last_updated_label_project_progress_percent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("image", models.ImageField(upload_to="gallery/")),
                ("caption", models.CharField(blank=True, max_length=300)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text='Optional grouping, e.g. "Solar" or "Switchgear".',
                        max_length=80,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "related_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gallery_images",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-id"],
            },
        ),
    ]
