# Generated by Django 5.2.15 on 2026-06-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_center", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("file", models.FileField(upload_to="downloads/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("company_profile", "Company Profile"),
                            ("capability_statement", "Capability Statement"),
                            ("brochure", "Brochure"),
                        ],
                        default="company_profile",
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_public", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
    ]
