# Generated by Django 5.2.15 on 2026-06-09 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_seed_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing')], default='completed', max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='Client / employer')),
                ('main_contractor', models.CharField(blank=True, max_length=255)),
                ('consultant', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(default='Tanzania', max_length=100)),
                ('sector', models.CharField(blank=True, choices=[('aviation', 'Aviation'), ('government', 'Government'), ('education', 'Education'), ('housing', 'Housing'), ('institutional', 'Institutional'), ('commercial', 'Commercial'), ('infrastructure', 'Infrastructure'), ('other', 'Other')], max_length=20)),
                ('role', models.CharField(blank=True, choices=[('prime', 'Prime Contractor'), ('sub', 'Sub-Contractor'), ('jv', 'Joint Venture Partner'), ('nominated', 'Nominated Sub-Contractor')], max_length=20)),
                ('year_start', models.PositiveIntegerField(blank=True, null=True)),
                ('year_end', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('overview', models.TextField(blank=True)),
                ('scope_of_work', models.TextField(blank=True, help_text='One item per line.')),
                ('technical_highlights', models.TextField(blank=True, help_text='One item per line.')),
                ('outcome', models.TextField(blank=True)),
                ('contract_value', models.CharField(blank=True, help_text="As documented, e.g. 'TZS 1,739,536,075'.", max_length=160)),
                ('contract_value_visible', models.BooleanField(default=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the homepage.')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('related_services', models.ManyToManyField(blank=True, related_name='projects', to='services.service')),
            ],
            options={
                'ordering': ['order', '-year_end', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('show_in_gallery', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
