# Generated by Django 5.2.15 on 2026-06-12 09:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_seed_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_updated_label",
            field=models.DateField(
                blank=True,
                help_text='The "Last updated" date shown on ongoing-project surfaces.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Ongoing projects only — overall completion from 0 to 100.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.CreateModel(
            name="ProjectMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "date",
                    models.DateField(blank=True, help_text="Target or completion date.", null=True),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("note", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="projects/updates/")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
    ]
