# Generated by Django 5.2.15 on 2026-06-14 20:39

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_last_updated_label_project_progress_percent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalProject",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                ("og_image", models.TextField(blank=True, max_length=100, null=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=270)),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Completed"), ("ongoing", "Ongoing")],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Client / employer"),
                ),
                ("main_contractor", models.CharField(blank=True, max_length=255)),
                ("consultant", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("country", models.CharField(default="Tanzania", max_length=100)),
                (
                    "sector",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("aviation", "Aviation"),
                            ("government", "Government"),
                            ("education", "Education"),
                            ("housing", "Housing"),
                            ("institutional", "Institutional"),
                            ("commercial", "Commercial"),
                            ("infrastructure", "Infrastructure"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("prime", "Prime Contractor"),
                            ("sub", "Sub-Contractor"),
                            ("jv", "Joint Venture Partner"),
                            ("nominated", "Nominated Sub-Contractor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("year_start", models.PositiveIntegerField(blank=True, null=True)),
                ("year_end", models.PositiveIntegerField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("overview", models.TextField(blank=True)),
                ("scope_of_work", models.TextField(blank=True, help_text="One item per line.")),
                (
                    "technical_highlights",
                    models.TextField(blank=True, help_text="One item per line."),
                ),
                ("outcome", models.TextField(blank=True)),
                (
                    "contract_value",
                    models.CharField(
                        blank=True,
                        help_text="As documented, e.g. 'TZS 1,739,536,075'.",
                        max_length=160,
                    ),
                ),
                ("contract_value_visible", models.BooleanField(default=True)),
                ("hero_image", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="Show on the homepage."),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Ongoing projects only — overall completion from 0 to 100.",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "last_updated_label",
                    models.DateField(
                        blank=True,
                        help_text='The "Last updated" date shown on ongoing-project surfaces.',
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical project",
                "verbose_name_plural": "historical projects",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
