from django.test import TestCase
from django.urls import reverse

from .models import Service


class ServiceModelTests(TestCase):
    def setUp(self):
        # Isolate from seeded services so counts are deterministic.
        Service.objects.all().delete()

    def test_slug_autogenerated(self):
        service = Service.objects.create(name="Power Lines")
        self.assertEqual(service.slug, "power-lines")

    def test_slug_is_unique(self):
        a = Service.objects.create(name="Same Name")
        b = Service.objects.create(name="Same Name")
        self.assertNotEqual(a.slug, b.slug)

    def test_capability_list_parsing(self):
        service = Service.objects.create(name="X", capabilities="A\n\n  B \n")
        self.assertEqual(service.capability_list, ["A", "B"])

    def test_featured_queryset_excludes_unpublished(self):
        Service.objects.create(name="Shown", is_featured=True, is_published=True)
        Service.objects.create(name="Hidden", is_featured=True, is_published=False)
        self.assertEqual(Service.objects.featured().count(), 1)


class ServicePublicTests(TestCase):
    def test_list_page_shows_seeded_service(self):
        response = self.client.get(reverse("services:list"))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Solar Street Lighting")

    def test_published_detail_page(self):
        service = Service.objects.create(name="Visible Service", is_published=True)
        response = self.client.get(service.get_absolute_url())
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Visible Service")

    def test_unpublished_detail_returns_404(self):
        service = Service.objects.create(name="Draft Service", is_published=False)
        response = self.client.get(reverse("services:detail", kwargs={"slug": service.slug}))
        self.assertEqual(response.status_code, 404)
