# Generated by Django 5.2.15 on 2026-06-09 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_seed_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('registration', 'Company Registration'), ('tax', 'Tax & Financial Compliance'), ('license', 'Trading License'), ('accreditation', 'Industry Accreditation'), ('safety', 'Health, Safety & Welfare'), ('completion', 'Project Completion')], max_length=20)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('number', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, help_text='Leave blank if it does not expire.', null=True)),
                ('file', models.FileField(blank=True, help_text='The certificate scan/PDF (offered as download-on-demand).', null=True, upload_to='certificates/')),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='certificates/thumbs/')),
                ('downloadable', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='projects.project')),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
