# Generated by Django 5.2.15 on 2026-06-14 20:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0002_seed_certificates"),
        ("projects", "0004_historicalproject"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCertificate",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("registration", "Company Registration"),
                            ("tax", "Tax & Financial Compliance"),
                            ("license", "Trading License"),
                            ("accreditation", "Industry Accreditation"),
                            ("safety", "Health, Safety & Welfare"),
                            ("completion", "Project Completion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("issuer", models.CharField(blank=True, max_length=200)),
                ("number", models.CharField(blank=True, max_length=120)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "valid_to",
                    models.DateField(
                        blank=True, help_text="Leave blank if it does not expire.", null=True
                    ),
                ),
                (
                    "file",
                    models.TextField(
                        blank=True,
                        help_text="The certificate scan/PDF (offered as download-on-demand).",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("display_image", models.TextField(blank=True, max_length=100, null=True)),
                ("downloadable", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical certificate",
                "verbose_name_plural": "historical certificates",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
