# Generated by Django 5.2.15 on 2026-06-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_create_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='DIEYNEM Co. Limited', max_length=200)),
                ('motto', models.CharField(default='Quality is our Motto', max_length=200)),
                ('po_box', models.CharField(blank=True, max_length=150, verbose_name='P.O. Box')),
                ('physical_address', models.TextField(blank=True)),
                ('phones', models.TextField(blank=True, help_text='One phone number per line.')),
                ('emails', models.TextField(blank=True, help_text='One email address per line.')),
                ('map_embed', models.TextField(blank=True, help_text='Google Maps embed URL (the src of the iframe).')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('footer_text', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('default_og_image', models.ImageField(blank=True, help_text='Default image used when pages are shared on social media.', null=True, upload_to='branding/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
