# Generated by Django 5.2.15 on 2026-06-14 20:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_seed_leadership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalClient",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(max_length=160)),
                ("logo", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("partner", "Partner"),
                            ("main_contractor", "Main Contractor"),
                        ],
                        default="client",
                        max_length=20,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "is_featured",
                    models.BooleanField(default=False, help_text="Highlight in the homepage band."),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical client",
                "verbose_name_plural": "historical clients",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSiteSetting",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("company_name", models.CharField(default="DIEYNEM Co. Limited", max_length=200)),
                ("motto", models.CharField(default="Quality is our Motto", max_length=200)),
                ("po_box", models.CharField(blank=True, max_length=150, verbose_name="P.O. Box")),
                ("physical_address", models.TextField(blank=True)),
                ("phones", models.TextField(blank=True, help_text="One phone number per line.")),
                ("emails", models.TextField(blank=True, help_text="One email address per line.")),
                (
                    "map_embed",
                    models.TextField(
                        blank=True, help_text="Google Maps embed URL (the src of the iframe)."
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("footer_text", models.TextField(blank=True)),
                ("logo", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "default_og_image",
                    models.TextField(
                        blank=True,
                        help_text="Default image used when pages are shared on social media.",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Site settings",
                "verbose_name_plural": "historical Site settings",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalStatistic",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("label", models.CharField(max_length=80)),
                ("value", models.PositiveIntegerField()),
                (
                    "prefix",
                    models.CharField(blank=True, help_text='e.g. "TZS " or "~".', max_length=10),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True, help_text='e.g. "+", " km" or "%".', max_length=10
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical statistic",
                "verbose_name_plural": "historical statistics",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTeamMember",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(max_length=160)),
                ("role", models.CharField(max_length=160)),
                (
                    "qualification",
                    models.CharField(
                        blank=True,
                        help_text='Honorific / qualification, e.g. "Eng." or "CPA".',
                        max_length=60,
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("leadership", "Leadership"),
                            ("engineer", "Engineering"),
                            ("support", "Support"),
                        ],
                        default="leadership",
                        max_length=20,
                    ),
                ),
                ("photo", models.TextField(blank=True, max_length=100, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical team member",
                "verbose_name_plural": "historical team members",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
