from django.test import TestCase
from django.urls import reverse

from apps.services.models import Service

from .models import Project, ProjectMilestone, ProjectUpdate


class ProjectModelTests(TestCase):
    def setUp(self):
        Project.objects.all().delete()

    def test_slug_autogenerated(self):
        project = Project.objects.create(title="Tabora Airport Works")
        self.assertEqual(project.slug, "tabora-airport-works")

    def test_slug_unique(self):
        a = Project.objects.create(title="Same")
        b = Project.objects.create(title="Same")
        self.assertNotEqual(a.slug, b.slug)

    def test_status_querysets(self):
        Project.objects.create(title="Done", status=Project.Status.COMPLETED)
        Project.objects.create(title="Doing", status=Project.Status.ONGOING)
        Project.objects.create(title="Hidden", status=Project.Status.ONGOING, is_published=False)
        self.assertEqual(Project.objects.completed().count(), 1)
        self.assertEqual(Project.objects.ongoing().count(), 1)

    def test_scope_and_highlight_lists(self):
        project = Project.objects.create(
            title="X", scope_of_work="A\n\nB\n", technical_highlights="H1\nH2"
        )
        self.assertEqual(project.scope_list, ["A", "B"])
        self.assertEqual(project.highlight_list, ["H1", "H2"])

    def test_year_display(self):
        ranged = Project.objects.create(title="A", year_start=2018, year_end=2019)
        single = Project.objects.create(title="B", year_end=2021)
        self.assertEqual(ranged.year_display, "2018–2019")
        self.assertEqual(single.year_display, "2021")

    def test_show_value_respects_visibility(self):
        hidden = Project.objects.create(title="H", contract_value="X", contract_value_visible=False)
        shown = Project.objects.create(title="S", contract_value="X", contract_value_visible=True)
        blank = Project.objects.create(title="Bl", contract_value="", contract_value_visible=True)
        self.assertFalse(hidden.show_value)
        self.assertTrue(shown.show_value)
        self.assertFalse(blank.show_value)

    def test_is_ongoing(self):
        ongoing = Project.objects.create(title="Live", status=Project.Status.ONGOING)
        done = Project.objects.create(title="Done", status=Project.Status.COMPLETED)
        self.assertTrue(ongoing.is_ongoing)
        self.assertFalse(done.is_ongoing)

    def test_display_progress_prefers_explicit_percent(self):
        project = Project.objects.create(
            title="P", status=Project.Status.ONGOING, progress_percent=65
        )
        ProjectMilestone.objects.create(project=project, title="A", is_complete=True)
        ProjectMilestone.objects.create(project=project, title="B", is_complete=False)
        # Explicit percent wins over the 50% the milestones would imply.
        self.assertEqual(project.display_progress, 65)

    def test_display_progress_falls_back_to_milestone_ratio(self):
        project = Project.objects.create(title="P", status=Project.Status.ONGOING)
        ProjectMilestone.objects.create(project=project, title="A", is_complete=True)
        ProjectMilestone.objects.create(project=project, title="B", is_complete=True)
        ProjectMilestone.objects.create(project=project, title="C", is_complete=False)
        ProjectMilestone.objects.create(project=project, title="D", is_complete=False)
        self.assertEqual(project.milestone_summary, (2, 4))
        self.assertEqual(project.display_progress, 50)

    def test_display_progress_none_when_nothing_to_show(self):
        project = Project.objects.create(title="P", status=Project.Status.ONGOING)
        self.assertIsNone(project.display_progress)

    def test_updates_ordered_newest_first(self):
        project = Project.objects.create(title="P", status=Project.Status.ONGOING)
        ProjectUpdate.objects.create(project=project, date="2026-01-01", note="old")
        ProjectUpdate.objects.create(project=project, date="2026-03-01", note="new")
        notes = [u.note for u in project.updates.all()]
        self.assertEqual(notes, ["new", "old"])


class ProjectPublicTests(TestCase):
    def test_list_shows_seeded_project(self):
        response = self.client.get(reverse("projects:list"))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Pan African Postal Union")

    def test_status_filter(self):
        response = self.client.get(reverse("projects:list"), {"status": "ongoing"})
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Msalato")
        self.assertNotContains(response, "Mkwawa University")

    def test_published_detail(self):
        project = Project.objects.create(title="Visible Project", is_published=True)
        response = self.client.get(project.get_absolute_url())
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Visible Project")

    def test_unpublished_detail_404(self):
        project = Project.objects.create(title="Draft Project", is_published=False)
        response = self.client.get(reverse("projects:detail", kwargs={"slug": project.slug}))
        self.assertEqual(response.status_code, 404)

    def test_list_has_header_and_cta(self):
        response = self.client.get(reverse("projects:list"))
        self.assertContains(response, "Project Portfolio")
        self.assertContains(response, "Request a Quotation")

    def test_detail_renders_case_study_sections(self):
        project = Project.objects.create(
            title="Switchgear Upgrade",
            is_published=True,
            scope_of_work="33kV switchgear\nTransformers",
        )
        response = self.client.get(project.get_absolute_url())
        self.assertContains(response, "Scope of work")
        self.assertContains(response, "33kV switchgear")
        self.assertContains(response, "Request a similar project")


class ProjectFilterTests(TestCase):
    def setUp(self):
        Project.objects.all().delete()
        self.electrical = Service.objects.create(name="Electrical Installations")
        self.ict = Service.objects.create(name="ICT & Structured Cabling")
        self.airport = Project.objects.create(
            title="Airport Wiring",
            status=Project.Status.ONGOING,
            sector=Project.Sector.AVIATION,
            country="Tanzania",
            is_published=True,
        )
        self.airport.related_services.add(self.electrical)
        self.school = Project.objects.create(
            title="School Network",
            status=Project.Status.COMPLETED,
            sector=Project.Sector.EDUCATION,
            country="Uganda",
            is_published=True,
        )
        self.school.related_services.add(self.ict)

    def _titles(self, response):
        return {p.title for p in response.context["projects"]}

    def test_sector_filter(self):
        response = self.client.get(reverse("projects:list"), {"sector": "aviation"})
        self.assertEqual(self._titles(response), {"Airport Wiring"})

    def test_country_filter(self):
        response = self.client.get(reverse("projects:list"), {"country": "Uganda"})
        self.assertEqual(self._titles(response), {"School Network"})

    def test_service_filter(self):
        response = self.client.get(reverse("projects:list"), {"service": self.ict.slug})
        self.assertEqual(self._titles(response), {"School Network"})

    def test_combined_filters_narrow_results(self):
        response = self.client.get(
            reverse("projects:list"), {"status": "ongoing", "sector": "aviation"}
        )
        self.assertEqual(self._titles(response), {"Airport Wiring"})
        # A conflicting pair yields nothing.
        empty = self.client.get(
            reverse("projects:list"), {"status": "completed", "sector": "aviation"}
        )
        self.assertEqual(self._titles(empty), set())

    def test_filter_options_only_list_used_values(self):
        response = self.client.get(reverse("projects:list"))
        sector_values = {v for v, _ in response.context["sectors"]}
        self.assertEqual(sector_values, {"aviation", "education"})
        self.assertEqual(response.context["countries"], ["Tanzania", "Uganda"])
        self.assertFalse(response.context["has_filters"])

    def test_htmx_request_returns_grid_partial_only(self):
        response = self.client.get(reverse("projects:list"), HTTP_HX_REQUEST="true")
        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, "public/projects/_grid.html")
        self.assertTemplateNotUsed(response, "public/base.html")
        self.assertNotContains(response, "filter-sector")

    def test_invalid_filter_values_ignored(self):
        response = self.client.get(reverse("projects:list"), {"status": "bogus", "sector": "nope"})
        self.assertEqual(self._titles(response), {"Airport Wiring", "School Network"})


class OngoingProjectsPublicTests(TestCase):
    def test_page_lists_only_published_ongoing(self):
        live = Project.objects.create(title="Msalato Airport Wiring", status=Project.Status.ONGOING)
        Project.objects.create(title="Finished Hall", status=Project.Status.COMPLETED)
        Project.objects.create(
            title="Hidden Live", status=Project.Status.ONGOING, is_published=False
        )
        response = self.client.get(reverse("ongoing_projects"))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, live.title)
        self.assertNotContains(response, "Finished Hall")
        self.assertNotContains(response, "Hidden Live")

    def test_page_shows_progress_milestones_and_updates(self):
        project = Project.objects.create(
            title="Live Works",
            status=Project.Status.ONGOING,
            progress_percent=70,
        )
        ProjectMilestone.objects.create(project=project, title="Cabling complete", is_complete=True)
        ProjectUpdate.objects.create(project=project, date="2026-06-01", note="Panel energised")
        response = self.client.get(reverse("ongoing_projects"))
        self.assertContains(response, "70%")
        self.assertContains(response, "Cabling complete")
        self.assertContains(response, "Panel energised")

    def test_progress_bar_is_animatable(self):
        Project.objects.create(
            title="Animated Works", status=Project.Status.ONGOING, progress_percent=70
        )
        response = self.client.get(reverse("ongoing_projects"))
        # The fill carries the JS hook class + the target width as a CSS var, so
        # public.js can animate it from 0 on scroll-in (no inline width to fight).
        self.assertContains(response, "progress-bar")
        self.assertContains(response, "--target: 70%")
        self.assertNotContains(response, 'style="width: 70%"')

    def test_empty_state(self):
        Project.objects.filter(status=Project.Status.ONGOING).delete()
        response = self.client.get(reverse("ongoing_projects"))
        self.assertContains(response, "No ongoing projects")

    def test_detail_shows_live_status_for_ongoing(self):
        project = Project.objects.create(
            title="Ongoing Case", status=Project.Status.ONGOING, progress_percent=40
        )
        ProjectMilestone.objects.create(project=project, title="Site handover", is_complete=True)
        response = self.client.get(project.get_absolute_url())
        self.assertContains(response, "Live status")
        self.assertContains(response, "40%")
        self.assertContains(response, "Site handover")

    def test_detail_hides_live_status_for_completed(self):
        project = Project.objects.create(title="Done Case", status=Project.Status.COMPLETED)
        response = self.client.get(project.get_absolute_url())
        self.assertNotContains(response, "Live status")
