from django.test import TestCase
from django.urls import reverse

from .models import Project


class ProjectModelTests(TestCase):
    def setUp(self):
        Project.objects.all().delete()

    def test_slug_autogenerated(self):
        project = Project.objects.create(title="Tabora Airport Works")
        self.assertEqual(project.slug, "tabora-airport-works")

    def test_slug_unique(self):
        a = Project.objects.create(title="Same")
        b = Project.objects.create(title="Same")
        self.assertNotEqual(a.slug, b.slug)

    def test_status_querysets(self):
        Project.objects.create(title="Done", status=Project.Status.COMPLETED)
        Project.objects.create(title="Doing", status=Project.Status.ONGOING)
        Project.objects.create(title="Hidden", status=Project.Status.ONGOING, is_published=False)
        self.assertEqual(Project.objects.completed().count(), 1)
        self.assertEqual(Project.objects.ongoing().count(), 1)

    def test_scope_and_highlight_lists(self):
        project = Project.objects.create(
            title="X", scope_of_work="A\n\nB\n", technical_highlights="H1\nH2"
        )
        self.assertEqual(project.scope_list, ["A", "B"])
        self.assertEqual(project.highlight_list, ["H1", "H2"])

    def test_year_display(self):
        ranged = Project.objects.create(title="A", year_start=2018, year_end=2019)
        single = Project.objects.create(title="B", year_end=2021)
        self.assertEqual(ranged.year_display, "2018–2019")
        self.assertEqual(single.year_display, "2021")

    def test_show_value_respects_visibility(self):
        hidden = Project.objects.create(title="H", contract_value="X", contract_value_visible=False)
        shown = Project.objects.create(title="S", contract_value="X", contract_value_visible=True)
        blank = Project.objects.create(title="Bl", contract_value="", contract_value_visible=True)
        self.assertFalse(hidden.show_value)
        self.assertTrue(shown.show_value)
        self.assertFalse(blank.show_value)


class ProjectPublicTests(TestCase):
    def test_list_shows_seeded_project(self):
        response = self.client.get(reverse("projects:list"))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Pan African Postal Union")

    def test_status_filter(self):
        response = self.client.get(reverse("projects:list"), {"status": "ongoing"})
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Msalato")
        self.assertNotContains(response, "Mkwawa University")

    def test_published_detail(self):
        project = Project.objects.create(title="Visible Project", is_published=True)
        response = self.client.get(project.get_absolute_url())
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Visible Project")

    def test_unpublished_detail_404(self):
        project = Project.objects.create(title="Draft Project", is_published=False)
        response = self.client.get(reverse("projects:detail", kwargs={"slug": project.slug}))
        self.assertEqual(response.status_code, 404)
